/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import controle.Gerenciamento;

/**
 *
 * @author natha
 */
public class JanelaCadastrarTreino extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JanelaCadastrarTreino.class.getName());
    private final Gerenciamento gerenciamento;

    /**
     * Creates new form JanelaCadastrarTreino
     */
    public JanelaCadastrarTreino(Gerenciamento gerenciamento) {
        this.gerenciamento = gerenciamento;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_titleCadastrarTreino = new javax.swing.JLabel();
        txt_tipoExercicio = new javax.swing.JLabel();
        txt_quantidadeExercicio = new javax.swing.JLabel();
        chkBox_costas = new javax.swing.JCheckBox();
        cb_quantPeito = new javax.swing.JComboBox<>();
        chkBox_peito = new javax.swing.JCheckBox();
        chkBox_biceps = new javax.swing.JCheckBox();
        chkBox_triceps = new javax.swing.JCheckBox();
        chkBox_quadriceps = new javax.swing.JCheckBox();
        chkBox_panturrilha = new javax.swing.JCheckBox();
        chkBox_glueto = new javax.swing.JCheckBox();
        chkBox_aerobico = new javax.swing.JCheckBox();
        cb_quantCostas = new javax.swing.JComboBox<>();
        cb_quantTriceps = new javax.swing.JComboBox<>();
        cb_quantQuadricpes = new javax.swing.JComboBox<>();
        cb_quantBiceps = new javax.swing.JComboBox<>();
        cb_quantGlueto = new javax.swing.JComboBox<>();
        cb_quantPanturrilha = new javax.swing.JComboBox<>();
        cb_quantAerobico = new javax.swing.JComboBox<>();
        txt_dificuldadeExercicio = new javax.swing.JLabel();
        cb_difCostas = new javax.swing.JComboBox<>();
        cb_difPeito = new javax.swing.JComboBox<>();
        cb_difBiceps = new javax.swing.JComboBox<>();
        cb_difTriceps = new javax.swing.JComboBox<>();
        cb_difQuadriceps = new javax.swing.JComboBox<>();
        cb_difGluteo = new javax.swing.JComboBox<>();
        cb_difPanturrilha = new javax.swing.JComboBox<>();
        cb_difAerobico = new javax.swing.JComboBox<>();
        btn_gerar = new javax.swing.JButton();
        btn_voltarGerarTreino = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt_titleCadastrarTreino.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txt_titleCadastrarTreino.setText("Cadastrar Treino");

        txt_tipoExercicio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_tipoExercicio.setText("Tipo do Exercicio");
        txt_tipoExercicio.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txt_tipoExercicioAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        txt_quantidadeExercicio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_quantidadeExercicio.setText("Quantidade de exercicios");
        txt_quantidadeExercicio.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txt_quantidadeExercicioAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        chkBox_costas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkBox_costas.setText("Costas");
        chkBox_costas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBox_costasActionPerformed(evt);
            }
        });

        cb_quantPeito.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cb_quantPeito.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        cb_quantPeito.setEnabled(false);

        chkBox_peito.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkBox_peito.setText("Peito");

        chkBox_biceps.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkBox_biceps.setText("Bíceps");
        chkBox_biceps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBox_bicepsActionPerformed(evt);
            }
        });

        chkBox_triceps.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkBox_triceps.setText("Tríceps");
        chkBox_triceps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBox_tricepsActionPerformed(evt);
            }
        });

        chkBox_quadriceps.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkBox_quadriceps.setText("Quadríceps");
        chkBox_quadriceps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBox_quadricepsActionPerformed(evt);
            }
        });

        chkBox_panturrilha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkBox_panturrilha.setText("Panturrilha");
        chkBox_panturrilha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBox_panturrilhaActionPerformed(evt);
            }
        });

        chkBox_glueto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkBox_glueto.setText("Glúteo");
        chkBox_glueto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBox_gluetoActionPerformed(evt);
            }
        });

        chkBox_aerobico.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkBox_aerobico.setText("Aeróbico");
        chkBox_aerobico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBox_aerobicoActionPerformed(evt);
            }
        });

        cb_quantCostas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cb_quantCostas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        cb_quantCostas.setEnabled(false);

        cb_quantTriceps.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cb_quantTriceps.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        cb_quantTriceps.setEnabled(false);

        cb_quantQuadricpes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cb_quantQuadricpes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        cb_quantQuadricpes.setEnabled(false);

        cb_quantBiceps.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cb_quantBiceps.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        cb_quantBiceps.setEnabled(false);

        cb_quantGlueto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cb_quantGlueto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        cb_quantGlueto.setEnabled(false);

        cb_quantPanturrilha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cb_quantPanturrilha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        cb_quantPanturrilha.setEnabled(false);

        cb_quantAerobico.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cb_quantAerobico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        cb_quantAerobico.setEnabled(false);

        txt_dificuldadeExercicio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_dificuldadeExercicio.setText("Dificuldade Exercicios");
        txt_dificuldadeExercicio.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txt_dificuldadeExercicioAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        cb_difCostas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cb_difCostas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Muito Leve", "Leve", "Médio", "Intermediário", "Difícil", "Muito Difícil", "Maromba" }));
        cb_difCostas.setEnabled(false);

        cb_difPeito.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cb_difPeito.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Muito Leve", "Leve", "Médio", "Intermediário", "Difícil", "Muito Difícil", "Maromba" }));
        cb_difPeito.setEnabled(false);

        cb_difBiceps.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cb_difBiceps.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Muito Leve", "Leve", "Médio", "Intermediário", "Difícil", "Muito Difícil", "Maromba" }));
        cb_difBiceps.setEnabled(false);

        cb_difTriceps.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cb_difTriceps.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Muito Leve", "Leve", "Médio", "Intermediário", "Difícil", "Muito Difícil", "Maromba" }));
        cb_difTriceps.setEnabled(false);

        cb_difQuadriceps.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cb_difQuadriceps.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Muito Leve", "Leve", "Médio", "Intermediário", "Difícil", "Muito Difícil", "Maromba" }));
        cb_difQuadriceps.setEnabled(false);

        cb_difGluteo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cb_difGluteo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Muito Leve", "Leve", "Médio", "Intermediário", "Difícil", "Muito Difícil", "Maromba" }));
        cb_difGluteo.setEnabled(false);

        cb_difPanturrilha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cb_difPanturrilha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Muito Leve", "Leve", "Médio", "Intermediário", "Difícil", "Muito Difícil", "Maromba" }));
        cb_difPanturrilha.setEnabled(false);

        cb_difAerobico.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cb_difAerobico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Muito Leve", "Leve", "Médio", "Intermediário", "Difícil", "Muito Difícil", "Maromba" }));
        cb_difAerobico.setEnabled(false);

        btn_gerar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_gerar.setText("Gerar");
        btn_gerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gerarActionPerformed(evt);
            }
        });

        btn_voltarGerarTreino.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_voltarGerarTreino.setText("Voltar");
        btn_voltarGerarTreino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarGerarTreinoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(chkBox_peito)
                                .addComponent(chkBox_biceps)
                                .addComponent(chkBox_triceps)
                                .addComponent(chkBox_quadriceps)
                                .addComponent(chkBox_panturrilha)
                                .addComponent(chkBox_glueto)
                                .addComponent(chkBox_aerobico)
                                .addComponent(chkBox_costas))
                            .addComponent(txt_tipoExercicio))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txt_quantidadeExercicio)
                                .addGap(18, 18, 18)
                                .addComponent(txt_dificuldadeExercicio))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cb_quantAerobico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cb_difAerobico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(cb_quantPanturrilha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cb_difPanturrilha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(cb_quantGlueto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cb_difGluteo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(cb_quantQuadricpes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cb_difQuadriceps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(cb_quantTriceps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cb_difTriceps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(cb_quantBiceps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cb_difBiceps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(cb_quantPeito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cb_difPeito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(cb_quantCostas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cb_difCostas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(27, 27, 27))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(btn_gerar)
                        .addGap(42, 42, 42)
                        .addComponent(btn_voltarGerarTreino)))
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txt_titleCadastrarTreino)
                .addGap(226, 226, 226))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(txt_titleCadastrarTreino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_tipoExercicio)
                    .addComponent(txt_quantidadeExercicio)
                    .addComponent(txt_dificuldadeExercicio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkBox_peito)
                    .addComponent(cb_quantPeito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_difPeito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkBox_costas)
                    .addComponent(cb_quantCostas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_difCostas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkBox_biceps)
                    .addComponent(cb_quantBiceps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_difBiceps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkBox_triceps)
                    .addComponent(cb_quantTriceps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_difTriceps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkBox_quadriceps)
                    .addComponent(cb_quantQuadricpes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_difQuadriceps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkBox_glueto)
                    .addComponent(cb_quantGlueto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_difGluteo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkBox_panturrilha)
                    .addComponent(cb_quantPanturrilha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_difPanturrilha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkBox_aerobico)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cb_quantAerobico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cb_difAerobico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_gerar)
                    .addComponent(btn_voltarGerarTreino))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_tipoExercicioAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txt_tipoExercicioAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tipoExercicioAncestorAdded

    private void txt_quantidadeExercicioAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txt_quantidadeExercicioAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_quantidadeExercicioAncestorAdded

    private void chkBox_costasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBox_costasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkBox_costasActionPerformed

    private void chkBox_bicepsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBox_bicepsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkBox_bicepsActionPerformed

    private void chkBox_tricepsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBox_tricepsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkBox_tricepsActionPerformed

    private void chkBox_quadricepsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBox_quadricepsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkBox_quadricepsActionPerformed

    private void chkBox_panturrilhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBox_panturrilhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkBox_panturrilhaActionPerformed

    private void chkBox_gluetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBox_gluetoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkBox_gluetoActionPerformed

    private void chkBox_aerobicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBox_aerobicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkBox_aerobicoActionPerformed

    private void txt_dificuldadeExercicioAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txt_dificuldadeExercicioAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_dificuldadeExercicioAncestorAdded

    private void btn_gerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gerarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_gerarActionPerformed

    private void btn_voltarGerarTreinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarGerarTreinoActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btn_voltarGerarTreinoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_gerar;
    private javax.swing.JButton btn_voltarGerarTreino;
    private javax.swing.JComboBox<String> cb_difAerobico;
    private javax.swing.JComboBox<String> cb_difBiceps;
    private javax.swing.JComboBox<String> cb_difCostas;
    private javax.swing.JComboBox<String> cb_difGluteo;
    private javax.swing.JComboBox<String> cb_difPanturrilha;
    private javax.swing.JComboBox<String> cb_difPeito;
    private javax.swing.JComboBox<String> cb_difQuadriceps;
    private javax.swing.JComboBox<String> cb_difTriceps;
    private javax.swing.JComboBox<String> cb_quantAerobico;
    private javax.swing.JComboBox<String> cb_quantBiceps;
    private javax.swing.JComboBox<String> cb_quantCostas;
    private javax.swing.JComboBox<String> cb_quantGlueto;
    private javax.swing.JComboBox<String> cb_quantPanturrilha;
    private javax.swing.JComboBox<String> cb_quantPeito;
    private javax.swing.JComboBox<String> cb_quantQuadricpes;
    private javax.swing.JComboBox<String> cb_quantTriceps;
    private javax.swing.JCheckBox chkBox_aerobico;
    private javax.swing.JCheckBox chkBox_biceps;
    private javax.swing.JCheckBox chkBox_costas;
    private javax.swing.JCheckBox chkBox_glueto;
    private javax.swing.JCheckBox chkBox_panturrilha;
    private javax.swing.JCheckBox chkBox_peito;
    private javax.swing.JCheckBox chkBox_quadriceps;
    private javax.swing.JCheckBox chkBox_triceps;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txt_dificuldadeExercicio;
    private javax.swing.JLabel txt_quantidadeExercicio;
    private javax.swing.JLabel txt_tipoExercicio;
    private javax.swing.JLabel txt_titleCadastrarTreino;
    // End of variables declaration//GEN-END:variables
}
