/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import controle.Gerenciamento;
import exceptions.UsuarioExistente;

import javax.swing.*;
import java.awt.*;
import java.security.NoSuchAlgorithmException;
import java.util.Arrays;

/**
 *
 * @author natha
 */
public class JanelaCadastro extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JanelaCadastro.class.getName());
    private final Gerenciamento gerenciamento;

    /**
     * Creates new form JanelaCadastro
     */
    public JanelaCadastro(Gerenciamento gerenciamento) {
        this.gerenciamento = gerenciamento;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_titleCadastro = new javax.swing.JLabel();
        txt_senhaCadastro = new javax.swing.JLabel();
        txt_usuarioCadastro = new javax.swing.JLabel();
        txtF_usuarioCadastro = new javax.swing.JTextField();
        txtF_senhaCadastro = new javax.swing.JPasswordField();
        txt_nomeCadastro = new javax.swing.JLabel();
        txtF_nomeCadastro1 = new javax.swing.JTextField();
        txt_emailCadastro = new javax.swing.JLabel();
        txtF_emailCadastro2 = new javax.swing.JTextField();
        txt_telefoneCadastro = new javax.swing.JLabel();
        txtF_telefoneCadastro3 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btn_cadastrar = new javax.swing.JButton();
        btn_voltarCadastro = new javax.swing.JButton();

        setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);

        txt_titleCadastro.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txt_titleCadastro.setText("CADASTRO");

        txt_senhaCadastro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_senhaCadastro.setText("Senha: ");
        txt_senhaCadastro.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txt_senhaCadastroAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        txt_usuarioCadastro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_usuarioCadastro.setText("Usuário: ");
        txt_usuarioCadastro.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txt_usuarioCadastroAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        txtF_usuarioCadastro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtF_senhaCadastro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtF_senhaCadastro.setEchoChar('*');
        txtF_senhaCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtF_senhaCadastroActionPerformed(evt);
            }
        });

        txt_nomeCadastro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_nomeCadastro.setText("Nome:");
        txt_nomeCadastro.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txt_nomeCadastroAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        txtF_nomeCadastro1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txt_emailCadastro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_emailCadastro.setText("Email: ");
        txt_emailCadastro.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txt_emailCadastroAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        txtF_emailCadastro2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txt_telefoneCadastro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_telefoneCadastro.setText("Telefone: ");
        txt_telefoneCadastro.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txt_telefoneCadastroAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        txtF_telefoneCadastro3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btn_cadastrar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_cadastrar.setText("Cadastrar");
        btn_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarActionPerformed(evt);
            }
        });

        btn_voltarCadastro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_voltarCadastro.setText("Voltar");
        btn_voltarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarCadastroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addComponent(btn_cadastrar)
                .addGap(48, 48, 48)
                .addComponent(btn_voltarCadastro)
                .addGap(106, 106, 106))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_cadastrar, btn_voltarCadastro});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cadastrar)
                    .addComponent(btn_voltarCadastro))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_usuarioCadastro)
                            .addComponent(txt_nomeCadastro)
                            .addComponent(txt_emailCadastro)
                            .addComponent(txt_telefoneCadastro)
                            .addComponent(txt_senhaCadastro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtF_telefoneCadastro3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                            .addComponent(txtF_emailCadastro2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtF_nomeCadastro1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtF_usuarioCadastro, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtF_senhaCadastro)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(txt_titleCadastro)
                .addGap(181, 181, 181))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(txt_titleCadastro)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_usuarioCadastro)
                    .addComponent(txtF_usuarioCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nomeCadastro)
                    .addComponent(txtF_nomeCadastro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_emailCadastro)
                    .addComponent(txtF_emailCadastro2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_telefoneCadastro)
                    .addComponent(txtF_telefoneCadastro3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_senhaCadastro)
                    .addComponent(txtF_senhaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_senhaCadastroAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txt_senhaCadastroAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_senhaCadastroAncestorAdded

    private void txt_usuarioCadastroAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txt_usuarioCadastroAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usuarioCadastroAncestorAdded

    private void txtF_senhaCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtF_senhaCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtF_senhaCadastroActionPerformed

    private void btn_voltarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarCadastroActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btn_voltarCadastroActionPerformed

    private void btn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarActionPerformed
        // TODO add your handling code here:
        char[] pwdChars = txtF_senhaCadastro.getPassword();
        String pwd = (pwdChars == null) ? "" : new String(pwdChars);
        if (txtF_usuarioCadastro.getText().isBlank() || txtF_nomeCadastro1.getText().isBlank() || txtF_emailCadastro2.getText().isBlank() || pwd.isBlank()){
            JOptionPane.showMessageDialog(getParent(), "Favor preencher todos os campos!", "", JOptionPane.ERROR_MESSAGE);
        }
        else{
            try {
                gerenciamento.CadastrarPessoa(txtF_usuarioCadastro.getText(), txtF_nomeCadastro1.getText(), txtF_emailCadastro2.getText(), txtF_telefoneCadastro3.getText(), Arrays.toString(txtF_senhaCadastro.getPassword()));
                JOptionPane.showMessageDialog(getParent(), "Usuário criado com sucesso!", "", JOptionPane.INFORMATION_MESSAGE);
                btn_voltarCadastro.doClick();
            }
            catch(NoSuchAlgorithmException e){
                JOptionPane.showMessageDialog(getParent(), "Erro criando usuário!", "", JOptionPane.ERROR_MESSAGE);
            }
            catch (UsuarioExistente e){
                JOptionPane.showMessageDialog(getParent(), "Nome de usuário ja existe!", "", JOptionPane.ERROR_MESSAGE);
                txtF_usuarioCadastro.setBorder(BorderFactory.createLineBorder(Color.RED));
            }
        }
    }//GEN-LAST:event_btn_cadastrarActionPerformed

    private void txt_nomeCadastroAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txt_nomeCadastroAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nomeCadastroAncestorAdded

    private void txt_emailCadastroAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txt_emailCadastroAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailCadastroAncestorAdded

    private void txt_telefoneCadastroAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txt_telefoneCadastroAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_telefoneCadastroAncestorAdded

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cadastrar;
    private javax.swing.JButton btn_voltarCadastro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtF_emailCadastro2;
    private javax.swing.JTextField txtF_nomeCadastro1;
    private javax.swing.JPasswordField txtF_senhaCadastro;
    private javax.swing.JTextField txtF_telefoneCadastro3;
    private javax.swing.JTextField txtF_usuarioCadastro;
    private javax.swing.JLabel txt_emailCadastro;
    private javax.swing.JLabel txt_nomeCadastro;
    private javax.swing.JLabel txt_senhaCadastro;
    private javax.swing.JLabel txt_telefoneCadastro;
    private javax.swing.JLabel txt_titleCadastro;
    private javax.swing.JLabel txt_usuarioCadastro;
    // End of variables declaration//GEN-END:variables
}
