/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import controle.Gerenciamento;
import exceptions.UsuarioOuSenhaIncorretos;

import javax.swing.*;
import java.awt.*;
import java.security.NoSuchAlgorithmException;
import java.util.Arrays;

/**
 *
 * @author natha
 */
public class JanelaLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JanelaLogin.class.getName());
    private final Gerenciamento gerenciamento;

    /**
     * Creates new form JanelaLogin
     */
    public JanelaLogin(Gerenciamento gerenciamento) {
        this.gerenciamento = gerenciamento;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_login = new javax.swing.JLabel();
        txt_senha = new javax.swing.JLabel();
        txt_usuario = new javax.swing.JLabel();
        txtF_usuario = new javax.swing.JTextField();
        txtF_senha = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        btn_entrar = new javax.swing.JButton();
        btn_cadastro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt_login.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txt_login.setText("LOGIN");

        txt_senha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_senha.setText("Senha: ");
        txt_senha.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txt_senhaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        txt_usuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_usuario.setText("Usuário: ");
        txt_usuario.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txt_usuarioAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        txtF_usuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtF_senha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtF_senha.setEchoChar('*');
        txtF_senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtF_senhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_senha)
                        .addGap(31, 31, 31)
                        .addComponent(txtF_senha))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_usuario)
                        .addGap(18, 18, 18)
                        .addComponent(txtF_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_login)
                .addGap(201, 201, 201))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(txt_login)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_usuario)
                    .addComponent(txtF_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_senha)
                    .addComponent(txtF_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        btn_entrar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_entrar.setText("Entrar");
        btn_entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_entrarActionPerformed(evt);
            }
        });

        btn_cadastro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_cadastro.setText("Cadastro");
        btn_cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(btn_entrar)
                .addGap(48, 48, 48)
                .addComponent(btn_cadastro)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_cadastro, btn_entrar});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_entrar)
                    .addComponent(btn_cadastro))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_senhaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txt_senhaAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_senhaAncestorAdded

    private void txt_usuarioAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txt_usuarioAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usuarioAncestorAdded

    private void btn_cadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastroActionPerformed
        // TODO add your handling code here:
        this.janelaCadastro = new JanelaCadastro(gerenciamento);
        janelaCadastro.setVisible(true);
    }//GEN-LAST:event_btn_cadastroActionPerformed

    private void txtF_senhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtF_senhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtF_senhaActionPerformed

    private void btn_entrarActionPerformed(java.awt.event.ActionEvent evt){
        try{
            if(gerenciamento.parseLogin(txtF_usuario.getText(), Arrays.toString(txtF_senha.getPassword()))){
                setVisible(false);
                this.janelaPrincipal = new JanelaPrincipal(gerenciamento);
                janelaPrincipal.setVisible(true);
            }
        } catch (NoSuchAlgorithmException e) {
            JOptionPane.showMessageDialog(getParent(), "Erro fazendo login!", "", JOptionPane.ERROR_MESSAGE);
        } catch (UsuarioOuSenhaIncorretos e) {
            JOptionPane.showMessageDialog(getParent(), "Usuario ou senha incorretos!", "", JOptionPane.ERROR_MESSAGE);
            btn_entrar.setBorder(BorderFactory.createLineBorder(Color.RED)); //gambiarra melhorar essa borda
        }
    }

    private JanelaPrincipal janelaPrincipal;
    private JanelaCadastro janelaCadastro;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cadastro;
    private javax.swing.JButton btn_entrar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField txtF_senha;
    private javax.swing.JTextField txtF_usuario;
    private javax.swing.JLabel txt_login;
    private javax.swing.JLabel txt_senha;
    private javax.swing.JLabel txt_usuario;
    // End of variables declaration//GEN-END:variables
}
