/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import controle.Gerenciamento;
import exceptions.LeituraEscritaException;

import javax.swing.*;
import java.security.NoSuchAlgorithmException;
import java.util.Arrays;

/**
 *
 * @author natha
 */
public class JanelaPerfil extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JanelaPerfil.class.getName());
    private final Gerenciamento gerenciamento;

    /**
     * Creates new form JanelaPerfil
     */
    public JanelaPerfil(Gerenciamento gerenciamento) {
        this.gerenciamento = gerenciamento;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_titlePerfil = new javax.swing.JLabel();
        txt_usuarioPerfil = new javax.swing.JLabel();
        txt_nomePerfil = new javax.swing.JLabel();
        txt_emailPerfil = new javax.swing.JLabel();
        txt_telefonePerfil = new javax.swing.JLabel();
        btn_alterar = new javax.swing.JButton();
        btn_voltarPerfil = new javax.swing.JButton();
        txtF_usuario = new javax.swing.JTextField();
        txtF_email = new javax.swing.JTextField();
        txtF_telefone = new javax.swing.JTextField();
        txtF_nome = new javax.swing.JTextField();
        txt_senhaPerfil = new javax.swing.JLabel();
        txtF_senha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);

        txt_titlePerfil.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txt_titlePerfil.setText("Meu Perfil");

        txt_usuarioPerfil.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_usuarioPerfil.setText("Usuário: ");
        txt_usuarioPerfil.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txt_usuarioPerfilAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        txt_nomePerfil.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_nomePerfil.setText("Nome:");
        txt_nomePerfil.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txt_nomePerfilAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        txt_emailPerfil.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_emailPerfil.setText("Email: ");
        txt_emailPerfil.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txt_emailPerfilAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        txt_telefonePerfil.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_telefonePerfil.setText("Telefone: ");
        txt_telefonePerfil.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txt_telefonePerfilAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        btn_alterar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_alterar.setText("Alterar");
        btn_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alterarActionPerformed(evt);
            }
        });

        btn_voltarPerfil.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_voltarPerfil.setText("Voltar");
        btn_voltarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarPerfilActionPerformed(evt);
            }
        });

        txtF_usuario.setEditable(false);
        txtF_usuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtF_email.setEditable(false);
        txtF_email.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtF_telefone.setEditable(false);
        txtF_telefone.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtF_nome.setEditable(false);
        txtF_nome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txt_senhaPerfil.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_senhaPerfil.setText("Senha:");
        txt_senhaPerfil.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txt_senhaPerfilAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        txtF_senha.setEditable(false);
        txtF_senha.setEchoChar('*');
        txtF_senha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtF_usuario.setText(gerenciamento.getUsuarioLogado().getUsuario());
        txtF_email.setText(gerenciamento.getUsuarioLogado().getEmail());
        txtF_nome.setText(gerenciamento.getUsuarioLogado().getNome());
        txtF_telefone.setText(gerenciamento.getUsuarioLogado().getTelefone());
        txtF_senha.setText("12345678");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_emailPerfil)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_usuarioPerfil)
                            .addComponent(txt_nomePerfil))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtF_email, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtF_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtF_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_telefonePerfil)
                            .addComponent(txt_senhaPerfil))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtF_telefone, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(txtF_senha))))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_titlePerfil)
                        .addGap(142, 142, 142))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_alterar)
                        .addGap(42, 42, 42)
                        .addComponent(btn_voltarPerfil)
                        .addGap(91, 91, 91))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_titlePerfil)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtF_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_usuarioPerfil))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nomePerfil)
                    .addComponent(txtF_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_emailPerfil)
                    .addComponent(txtF_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_telefonePerfil)
                    .addComponent(txtF_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_senhaPerfil)
                    .addComponent(txtF_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_alterar)
                    .addComponent(btn_voltarPerfil))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.SwingUtilities.invokeLater(() -> jPanel1.requestFocusInWindow());

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_usuarioPerfilAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txt_usuarioPerfilAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usuarioPerfilAncestorAdded

    private void txt_nomePerfilAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txt_nomePerfilAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nomePerfilAncestorAdded

    private void txt_emailPerfilAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txt_emailPerfilAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailPerfilAncestorAdded

    private void txt_telefonePerfilAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txt_telefonePerfilAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_telefonePerfilAncestorAdded

    private void btn_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alterarActionPerformed
        // TODO add your handling code here:
        String face = ((JButton)evt.getSource()).getText();
        if (face.equals("Alterar")) {
            // Deixar os texts fields editaveis para alteracao
            txtF_nome.setEditable(true);
            txtF_email.setEditable(true);
            txtF_telefone.setEditable(true);
            txtF_senha.setEditable(true);
            txtF_senha.setText("");

            // Mudar a face do botao para Salvar
            btn_alterar.setText("Salvar");

        } else {
            // Deixar os texts fields nao editaveis
            txtF_nome.setEditable(false);
            txtF_email.setEditable(false);
            txtF_telefone.setEditable(false);
            txtF_senha.setEditable(false);

            try {
                char[] pwdChars = txtF_senha.getPassword();
                String pwd = (pwdChars == null) ? "" : new String(pwdChars);
                if (pwd.isBlank()){
                    gerenciamento.alterarPessoa(txtF_nome.getText(), txtF_email.getText(), txtF_telefone.getText(), pwd);
                }
                else{
                    gerenciamento.alterarPessoa(txtF_nome.getText(), txtF_email.getText(), txtF_telefone.getText(), Arrays.toString(txtF_senha.getPassword()));
                }
            }
            catch (NoSuchAlgorithmException e){
                JOptionPane.showMessageDialog(getParent(), "Erro alterando usuário!", "", JOptionPane.ERROR_MESSAGE);
            }
            catch (LeituraEscritaException e){
                JOptionPane.showMessageDialog(getParent(), "Erro salvando usuário!", "", JOptionPane.ERROR_MESSAGE);
            }

            // Mudar a face do botao para Alterar
            btn_alterar.setText("Alterar");

            // Mensagem de confirmacao da alteracao
            JOptionPane.showMessageDialog(this, "Perfil Alterado com Sucesso", "Alteracao", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_alterarActionPerformed

    private void btn_voltarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarPerfilActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btn_voltarPerfilActionPerformed

    private void txt_senhaPerfilAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txt_senhaPerfilAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_senhaPerfilAncestorAdded

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_alterar;
    private javax.swing.JButton btn_voltarPerfil;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtF_senha;
    private javax.swing.JTextField txtF_email;
    private javax.swing.JTextField txtF_nome;
    private javax.swing.JTextField txtF_telefone;
    private javax.swing.JTextField txtF_usuario;
    private javax.swing.JLabel txt_emailPerfil;
    private javax.swing.JLabel txt_nomePerfil;
    private javax.swing.JLabel txt_senhaPerfil;
    private javax.swing.JLabel txt_telefonePerfil;
    private javax.swing.JLabel txt_titlePerfil;
    private javax.swing.JLabel txt_usuarioPerfil;
    // End of variables declaration//GEN-END:variables
}
