package visao;

import controle.Gerenciamento;

import java.awt.*;

/**
 * Janela de visualização da ficha de treino do usuário.
 * 
 * <p>Exibe a lista completa de exercícios da ficha de treino atual do usuário logado,
 * incluindo detalhes como repetições, séries, carga e tempo de duração.</p>
 * 
 * <p><b>Formato de exibição:</b></p>
 * <ul>
 *   <li><b>Aeróbico:</b> Nome - Tempo: X minutos</li>
 *   <li><b>Anaeróbico:</b> GRUPO: Nome - Repetições: RxS - Sug. carga: Xkg</li>
 * </ul>
 * 
 * @author natha
 * @version 1.0
 * @see Gerenciamento#verTreino
 */
public class JanelaVerTreino extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JanelaVerTreino.class.getName());
    private final Gerenciamento gerenciamento;

    /**
     * Creates new form JanelaVerTreino
     */
    public JanelaVerTreino(Gerenciamento gerenciamento) {
        this.gerenciamento = gerenciamento;
        initComponents();
        txtPane_treino.setText(gerenciamento.verTreino());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_titleCadastrarTreino = new javax.swing.JLabel();
        btn_voltarGerarTreino = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPane_treino = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt_titleCadastrarTreino.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txt_titleCadastrarTreino.setText("Treino");

        btn_voltarGerarTreino.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_voltarGerarTreino.setText("Voltar");
        btn_voltarGerarTreino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarGerarTreinoActionPerformed(evt);
            }
        });

        txtPane_treino.setFont(new Font("SansSerif", Font.BOLD, 18));
        txtPane_treino.setForeground(Color.BLACK);
        jScrollPane1.setViewportView(txtPane_treino);
        txtPane_treino.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(txt_titleCadastrarTreino))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(btn_voltarGerarTreino)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(txt_titleCadastrarTreino)
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btn_voltarGerarTreino)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_voltarGerarTreinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarGerarTreinoActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btn_voltarGerarTreinoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_voltarGerarTreino;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane txtPane_treino;
    private javax.swing.JLabel txt_titleCadastrarTreino;
    // End of variables declaration//GEN-END:variables
}
